services:
  db:
    image: postgres:15-alpine
    container_name: url_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: url_cache
    ports:
      - "6379:6379"